<a href="https://colab.research.google.com/github/SheikhQais/numpy/blob/main/Numpy_Indexing%26Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Indexing in Numpy**

### **Indexing refers to accessing to a single element in an array**
indexing starts from 0 to onwards

In [ ]:
import numpy as np
'''
array[index] #for 1d array
array[row, column] #2d array
'''

arr = np.array([1,2,3,4,5])
print(arr[0])
print(arr[2])
print(arr[-1]) #negative indexing, index-> -1 = 5

1
3
5


In [ ]:
# array[row, column] -> for 2d array
d_arr = np.array([[1,2,3,4], [5,6,7,8]])
print(d_arr[0,1])
print(d_arr[1,3])

2
8


## **Slicing**

### Accessing a sub-array or subset of array

array[start, end, step]
end-1
step -> default_value = 0

In [ ]:
print(arr[0:3])
print(arr[:4])
print(arr[1:])
print(arr[::2])
print(arr[::-1]) # Give no start, no end, step is -1, it will reverse the array

[1 2 3]
[1 2 3 4]
[2 3 4 5]
[1 3 5]
[5 4 3 2 1]


## **Fency Indexing**
slecting multiple elements at once, In this, we will pass the multiple indexes in a list

In [ ]:
print(arr[[1,3,4]])

[2 4 5]
