<a href="https://colab.research.google.com/github/SheikhQais/numpy/blob/main/Numpy_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy **Operations**

## Shape of Array

In [5]:
import numpy as np

array_2d = np.array([[1,2,3,4],[5,6,7,8]])
print(array_2d)
print(array_2d.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


## Size of Array

This size() method shows, how many element are there in the array. In other way, if there is a data of items getting manufactured in the factory then, it's show how many items are there in the data.

In [7]:
d_array = np.array([
    [10,20,30],
    [80,90,100]
])
print(d_array.size)

6


## ndim

How may dimensions are there in the array.

In [14]:
_3darray = np.array([[
                      [1,2,3,4,5,6.06],
                      [7,5,4,3,2,1.1]
                      ]])
print(d_array.ndim)
print(_3darray.ndim)

2
3


## dtype

This shows the datatype of element.

In [16]:
print(_3darray.dtype)
'''
In this array, I've added 1 or 2 float values that will show that datatype of
this array will be Float, so, you can do operations according to this.
'''

float64


"\nIn this array, I've added 1 or 2 float values that will show that datatype of\nthis array will be Float, so, you can do operations according to this.\n"

## astype()

arr.astype(new datatype)

In [19]:
print(_3darray.dtype)
new_int_array = _3darray.astype(int)
print(new_int_array)
print(new_int_array.dtype)

float64
[[[1 2 3 4 5 6]
  [7 5 4 3 2 1]]]
int64


## Mathematical Operations in Numpy

In [24]:
print(new_int_array + 10)
print(new_int_array - 1)
print(new_int_array * 10)
print(new_int_array / 10, '\n' ,new_int_array.dtype)
''' Datatype will be same as we are not making
 any change in the array.
'''
print(new_int_array)

[[[11 12 13 14 15 16]
  [17 15 14 13 12 11]]]
[[[0 1 2 3 4 5]
  [6 4 3 2 1 0]]]
[[[10 20 30 40 50 60]
  [70 50 40 30 20 10]]]
[[[0.1 0.2 0.3 0.4 0.5 0.6]
  [0.7 0.5 0.4 0.3 0.2 0.1]]] 
 int64
[[[1 2 3 4 5 6]
  [7 5 4 3 2 1]]]


## Aggregation Functions

np.sum() Sum of all elements
np.mean() Mean value of all elements
np.min() Minimum value in elements
np.max() Maximum value in elements
np.std() Standard Deviation of elements
np.var() Variance of elements

In [26]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.var(arr))

45
1
9
5.0
2.581988897471611
6.666666666666667
