<a href="https://colab.research.google.com/github/SheikhQais/numpy/blob/main/Reshaping%26Manipulating.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Reshaping and Manipulating Data in Numpy

## Reshaping:
changing the dimension of array without changing or modifying data in array.

In [3]:
"""
reshape() doesn’t modify the original array — it returns a reshaped version.
You gotta store it in a variable (like newarr) or reassign it back to arr if you want to keep the new shape
"""
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(arr, '\n', newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


## Flattening Arrays

When you need to convert multi-Dimensional array into 1D array.
arr.ravel() -> View
arr.flatten() ->  copy

In [4]:
import numpy as np
arr_2d = np.array([[1,2,3],[4,5,6]])

print(arr_2d.ravel())
print(arr_2d.flatten())

[1 2 3 4 5 6]
[1 2 3 4 5 6]
